Nblar shopping cart easy
girlscript-blr/code-with-girlscript-bangalore pull request #1
Opened 2020-06-30 15:41 UTC by nblar

2020-07-04 09:23 UTC, girlscript-blr commented
Please follow the below step for putting your solution in the right folder.
The codes/files should be inside a single folder following a specific naming convention. The solution folder name should be <your GitHub Id>_<your name>.

2020-07-25 09:15 UTC, girlscript-blr commented
Hello @nblar ,

This is to inform that, you will not receive your badge if your PR is merged after **31st July 2020**.
Please update the requested change requests before 31st July.

Thanks & Regards!

2020-07-26 04:43 UTC, girlscript-blr requested changes
Please rename the folder name as `<github username>_<your name>`

2020-07-26 04:43 UTC, girlscript-blr commented on Easy/1. Shopping Cart Problem/solutions/nblar/Opensource.java
> +              System.out.println("Payemnt Mode:- "+payment);
`Payment` spelling mistake.

2020-07-26 08:32 UTC, irshadjsr21 requested changes
1. The program should not exit after the shopping list is displayed.
![image](https://user-images.githubusercontent.com/40335357/88474833-0b283200-cf48-11ea-8315-503d08d30fd5.png)
2. I'm not getting the purchase list & date and time of purchase in the bill.
![image](https://user-images.githubusercontent.com/40335357/88474891-8ab60100-cf48-11ea-9e56-61eaafa70842.png)

3. The user should be able to buy only one item.

2020-08-06 09:02 UTC, closed without merging