Dhm medium
girlscript-blr/code-with-girlscript-bangalore pull request #113
Opened 2020-10-23 18:17 UTC by Prachi-05

2020-10-24 12:04 UTC, girlscript-blr requested changes
Please resolve the following change requests:
- **Database file** seems to be missing, please add it.  
![Screenshot 2020-10-24 at 1 02 59 PM](https://user-images.githubusercontent.com/54791364/97081189-5244c280-161e-11eb-9d1f-2aa95e7411d3.png)

- The app breaks when I enter some **invalid inputs.** Eg. If I enter height or weight in the string. User should be stated `invalid input, please enter integer` or something like that.
![Screenshot 2020-10-24 at 12 59 35 PM](https://user-images.githubusercontent.com/54791364/97081236-9afc7b80-161e-11eb-95e3-196da771a2d1.png)

- Also a suggestion: It will be better to **provide options** for `Gender: Male, Female, Other` and `Blood Groups: O+ AB+ B+ O- etc` so the user doesn't type anything wrong by mistake.

2020-10-24 13:11 UTC, Prachi-05 commented
@girlscript-blr made the changes

2020-10-25 17:25 UTC, girlscript-blr approved these changes

2020-10-25 17:26 UTC, merged

2020-10-25 17:29 UTC, girlscript-blr commented
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull request made in the `Medium` sections of the Problem Statement.

Congratulations🎊 🎉 on getting your pull request successfully merged in the **Digital Hospital Manager - Medium** section in **code-with-girlscript-bangalore** repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Also [RSVP here](https://tinyurl.com/gsblr-hacktoberfest2020) to win\* a limited edition **Hacktoberfest** 👕Tee-shirt or a 🎍plant if you haven't yet.

Learning is a never-ending process. 📈 Check out the [Hard](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/4.%20Digital%20Hospital%20Manager) and [Bonus](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Bonus/4.%20Digital%20Hospital%20Manager) level problem statements and try your hand at it for earning higher-level badges. 

Thanks for your contribution! 
Happy coding😃