IPL Management App -Medium
girlscript-blr/code-with-girlscript-bangalore pull request #130
Opened 2020-11-09 05:07 UTC by 4doctorstrange

Refer Read Me.txt to run application.

2020-11-10 18:07 UTC, girlscript-blr requested changes
Please modify the following change requests:
- There is supposed to be **56 matches**, but I see the loop is run twice because of which we are seeing **112 matches** in the table. Refer Screenshots:

![Screenshot 2020-11-10 at 11 32 15 PM](https://user-images.githubusercontent.com/54791364/98713415-99b4a800-23ad-11eb-9b42-229a1a633c8b.png)

![Screenshot 2020-11-10 at 11 32 43 PM](https://user-images.githubusercontent.com/54791364/98713444-a507d380-23ad-11eb-8638-dda00c4c8807.png)

2020-11-10 19:02 UTC, 4doctorstrange commented
HI, thanks for pointing that out. I have made the changes , let if know if their is any other bug.

2020-11-11 07:34 UTC, girlscript-blr approved these changes

2020-11-11 07:35 UTC, merged

2020-11-11 07:37 UTC, girlscript-blr commented
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull request made in the `Intermediate` sections of the Problem Statement.

Congratulations🎊 🎉 on getting your pull request successfully merged in the **IPL Management App - Medium** section in **code-with-girlscript-bangalore** repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈  Check out our [Hard](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/5.%20IPL%20Management%20App) level problem statements and try your hand at it for earning higher-level badges. 

Thanks for your contribution! 
Happy coding😃