Shopping cart problem -medium
girlscript-blr/code-with-girlscript-bangalore pull request #24
Opened 2020-07-04 16:52 UTC by AcidBurn18

2020-07-11 08:55 UTC, girlscript-blr requested changes
There seems to be a bug in your code, refer to the screenshot attached:
![Screenshot 2020-07-11 at 2 19 11 PM](https://user-images.githubusercontent.com/54791364/87220526-13963f80-c382-11ea-8561-6b086d8ee795.png)

2020-07-11 08:55 UTC, girlscript-blr commented on Medium/1. Shopping Cart Problem/solutions/AcidBurn18_AnshAgrawal/Solution
> +            more=input("Enter ypur choice:- ")
`your` is misspelled.

2020-07-11 10:18 UTC, AcidBurn18 commented on Medium/1. Shopping Cart Problem/solutions/AcidBurn18_AnshAgrawal/Solution
> +            more=input("Enter ypur choice:- ")
Done

2020-07-12 08:41 UTC, girlscript-blr requested changes
is this https://github.com/girlscript-blr/code-with-girlscript-bangalore/pull/24#pullrequestreview-446789443 change request resolved? I am still getting the same error:

`Traceback (most recent call last):
  File "/Volumes/Macintosh HD 2/MyCodes/ShoppingCartProblemPython/hello.py", line 62, in <module>
    d=shoplist[mapping[purchased[i]]]
KeyError: 'Graphic card'`

2020-07-12 08:41 UTC, girlscript-blr commented on Medium/1. Shopping Cart Problem/solutions/AcidBurn18_AnshAgrawal/Solution
> +    name=input("Entee=r the Customer Name: ")
spelling mistake.

2020-07-14 19:21 UTC, girlscript-blr approved these changes

2020-07-14 19:22 UTC, merged

2020-07-14 19:23 UTC, girlscript-blr commented
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull requests made in `MEDIUM` sections of the problem statement.

Congratulations🎊 🎉  on getting your pull request successfully merged in the `Shopping Cart Problem - Medium` section in `code-with-girlscript-bangalore` repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Check out our [Advanced](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/1.%20Shopping%20Cart%20Problem) level problem and try your hand at it to earn **THE AFICIONADO** 🥇 and **GEEK OF THE GEEKS** 🏆 badges. Thanks for your contribution! Happy coding😃