Simple Pacman Easy program in python
girlscript-blr/code-with-girlscript-bangalore pull request #74
Opened 2020-08-23 18:41 UTC by Prachi-05

Added a simple solution to Pacman Easy

2020-08-28 09:43 UTC, girlscript-blr requested changes
Here are the following changes need to be implemented
- Please send PR request for `girlscript-blr:solution` branch in place of girlscript-blr:master branch
- Please don't check in any other files outside your folder i.e. `Prachi-05_Prachi` Please remove the extra REAMDME.md files from Shopping Cart Problem, which is also checked in as it may lead to merging conflicts.
- Also add a README.md file or a .doc or .pdf file inside your folder i.e. `Prachi-05_Prachi` attaching screenshots of the output along with writing a few lines on the approach taken to solve the problem.

2020-08-29 06:50 UTC, Prachi-05 commented
Made the requested changes.

2020-08-29 09:27 UTC, girlscript-blr requested changes
I am seeing the existing files in the repo to have been deleted. If I try to merge your code, the same files in our solution branch will also get deleted.
![Screenshot 2020-08-29 at 1 57 17 PM](https://user-images.githubusercontent.com/54791364/91632625-c177af00-e9ff-11ea-96e5-a9edba12d5de.png)

To resolve these conflicts there are 2 approaches to resolve this conflict
- You can take a new fork from `girlscript-blr:master` branch, copy-paste your named folder i.e. `Prachi-05_Prachi` along with your Easy solution files inside your folder in `Easy/2. Pacman Game/solutions/` and send a new PR.
- You can add the deleted files back into your `PacmanEasy` branch and make it exactly the same as in our `girlscript-blr:master` branch.

You can try any of the approaches. if you get stuck or need our help feel free to let us know, we will be happy to help.

2020-08-29 09:27 UTC, girlscript-blr commented on Easy/2. Pacman Game/solutions/Prachi-05_Prachi/Pacman-Easy.py
> +        if(aself.maze[self.pacmanx+x][self.pacmany+y]!='|' and self.maze[self.pacmanx+x][self.pacmany+y]!='-'):
it should be **self** in place of aself.

2020-08-29 14:45 UTC, closed without merging

2020-08-29 16:13 UTC, girlscript-blr commented
The PR is continued with new PR #77