Solution for Covid 19 food supply easy
girlscript-blr/code-with-girlscript-bangalore pull request #86
Opened 2020-09-03 12:49 UTC by VarunSAthreya

2020-09-05 09:10 UTC, irshadjsr21 requested changes
Please send a PR to `girlscript-blr:solution` branch. Kindly refer to [CONTRIBUTING.md](https://github.com/girlscript-blr/code-with-girlscript-bangalore/blob/master/CONTRIBUTING.md) file's Create Pull Request point.

Now that you have created the PR, you can click on the `Edit` button beside the PR title and change the branch this PR is pointing to. Please follow the below steps.

1. Click on `Edit`.
![image](https://user-images.githubusercontent.com/40335357/86520924-8f1a5d00-be67-11ea-87e9-b4b1d9d57b98.png)

2. Change the base branch from `master` to `solution`.
![image](https://user-images.githubusercontent.com/40335357/86520931-a3f6f080-be67-11ea-85e3-9b57690e483c.png)

Also move the `Solutions.pdf` to the flutter directory, i.e., `VarunSAthreya`.

There are errors in running the flutter app on android, please resolve it.
![image](https://user-images.githubusercontent.com/40335357/92301954-9d7b1700-ef85-11ea-8575-16434ed53e30.png)

2020-09-06 11:13 UTC, VarunSAthreya commented
Changed the branch, and fixed the errors.

2020-09-08 06:44 UTC, irshadjsr21 approved these changes

2020-09-08 06:44 UTC, merged

2020-09-08 06:46 UTC, irshadjsr21 commented
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull request made in `Easy` sections of the Problem Statement.

Congratulations🎊 🎉 on getting your pull request successfully merged in the **COVID-19 Food Supply App** - Easy section in **code-with-girlscript-bangalore** repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Check out the [Medium](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Medium/3.%20COVID-19%20Food%20Supply%20App) and [Advanced](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/3.%20COVID-19%20Food%20Supply%20App) level problem statement and try your hand at it for earning higher-level badges. Thanks for your contribution! Happy coding😃